Testing to deploy
IBI-s-IT/ibi-lounge-backend pull request #9
Opened 2023-09-15 22:24 UTC by cullfy

fixes #7

2023-09-16 08:53 UTC, gbowsky requested changes

2023-09-16 08:53 UTC, gbowsky commented on src/utils/filterSubgroups.ts
> +    return filteredLessons;
почему вдруг `camelCase`?

2023-09-16 08:53 UTC, gbowsky commented on src/utils/parser/parser.ts
> -    } else if (subgroups.length > 1) {
Думаешь точно не стоит оставлять? Был такой кейс когда подгрупп в один день несколько.

2023-09-16 08:58 UTC, cullfy commented on src/utils/filterSubgroups.ts
> +    return filteredLessons;
потому что глаза выкалывает снейк в жс, но проф деформация идет порой, я ж кусок с пхп переписывал и имена оставил

2023-09-16 08:59 UTC, cullfy commented on src/utils/parser/parser.ts
> -    } else if (subgroups.length > 1) {
ну тогда надо subgroup?: string[], но никак не "1 и 2")
но я просто не видел такого кейса, потом могу доработать под него

2023-09-16 09:09 UTC, gbowsky commented on src/utils/parser/parser.ts
> -    } else if (subgroups.length > 1) {
Посмотри тесты, там всё есть.

2023-09-16 09:10 UTC, gbowsky commented on src/utils/filterSubgroups.ts
> +    return filteredLessons;
Давай консистентное форматирование в проекте иметь. Как раз занимаюсь интеграцией Docker, ESLint, Prettier чтобы споров таких не было.

2023-09-16 09:12 UTC, cullfy commented on src/utils/filterSubgroups.ts
> +    return filteredLessons;
окей, ну для жс же камел принят, нет разве?

2023-09-17 01:39 UTC, cullfy commented on src/utils/parser/parser.ts
> -    } else if (subgroups.length > 1) {
подогнал

2023-09-17 09:50 UTC, gbowsky requested changes

2023-09-17 09:50 UTC, gbowsky commented on src/utils/parser/parser.ts
> +  // text = text.trim();
кажется лишнее осталось)

2023-09-17 09:50 UTC, gbowsky commented on src/utils/filterSubgroups.ts
> +    return filteredLessons;
в фронтенд коде точно, для бекенд кода я бы предпочёл snake_case.

2023-09-17 10:23 UTC, cullfy commented on src/utils/parser/parser.ts
> +  // text = text.trim();
боже... да..

2023-09-17 11:48 UTC, gbowsky requested changes
Треды резолвит ревьювер.

2023-09-17 11:51 UTC, cullfy commented on src/utils/filterSubgroups.ts
> +    return filteredLessons;
не знаю, как по мне тут это определяет язык, а не применение

2023-09-17 12:04 UTC, gbowsky submitted a review, later dismissed
snake_case

2023-09-17 12:13 UTC, gbowsky submitted a review, later dismissed

2023-09-17 12:18 UTC, gbowsky approved these changes

2023-09-17 12:21 UTC, merged